### ISSUE TITLE
Consider changing to permissive or weak copyleft license

### ISSUE THREAD

**Issue by palmskog** [uds-psl/coq-library-fol#2]
To enable easier reuse of this library, please consider changing its license to a permissive license like [MIT](https://spdx.org/licenses/MIT.html) or a weak copyleft license like [MPL-2.0](https://spdx.org/licenses/MPL-2.0.html).

The issue with strong copyleft such as CeCILL-2.1 is that clients of the library will need to change their licenses to a strong copyleft license like CeCILL-2.1 itself or GPL, which they may not be prepared to do.

**Comment by palmskog** [comment]
@yforster now that coq-library-undecidability is under MPL and another license here is feasible, is it an option to put this library under a permissive license like MIT?

**Comment by dominik-kirst** [comment]
I've just replaced the license with the MIT license, thanks for the suggestion @palmskog :)

**Comment by JoJoDeveloping** [comment]
Since everyone is happy with this license, we can close this issue.
