### ISSUE TITLE
Releasing and packaging the library

### ISSUE THREAD

**Issue by palmskog** [uds-psl/coq-library-fol#3]
To enable easier reuse of the library, please consider releasing (tagging) and packaging it for major Coq versions in the [Coq opam archive](https://github.com/coq/opam) and elsewhere. Reuse potential would be even greater if #2 is taken into account also.

**Comment by dominik-kirst** [comment]
We plan to have an opam package available for 8.18 once the metacoq and the undecidability library opam packages are availble.

**Comment by dominik-kirst** [comment]
(And in that turn will also release packages for 8.16 and 8.17.)

**Comment by yforster** [comment]
Done: https://github.com/coq/opam/pull/2812 (v1.1+8.17 and v1.1.1+8.18)

**Comment by JoJoDeveloping** [comment]
Also done: https://github.com/coq/opam/pull/2825 (v1.0+8.17 and v1.0+8.18)

**Comment by palmskog** [comment]
Thanks!
